# Nombre del workflow que aparecerá en GitHub Actions
name: CI Pipeline

# Evento que dispara el workflow: cada push a las ramas main y develop
on:
  push:
    branches:
      - main      # Rama principal
      - develop   # Rama de desarrollo
      #- feature/* # Cualquier rama que empiece por feature/
      - feature/testing-prova      

# Definición de los jobs (tareas) que se ejecutarán
jobs:

  # --- JOB 1: FRONTEND ---
  frontend:
    runs-on: ubuntu-latest           # El job se ejecuta en un runner Linux(no pasa nada que tengamos windows)
    defaults:
      run:
        working-directory: Frontend  # Todas las acciones se ejecutan dentro de la carpeta Frontend
    steps:
      - uses: actions/checkout@v3    # Descarga el código del repositorio en el runner

      - name: Setup Node.js          # Instala Node.js en la versión especificada
        uses: actions/setup-node@v3
        with:
          node-version: '22.17.0'

      - name: Install dependencies   # Instala dependencias del proyecto Angular
        run: npm install

      - name: Lint boundaries        # Ejecuta ESLint con el plugin boundaries para validar arquitectura
        run: npm run lint:boundaries

      - name: Build Angular          # Compila el proyecto Angular en modo producción
        run: npm run build -- --configuration production
      
      - name: Tests Unitarios
        run: npm run test

# --- JOB 2: BACKEND (Ya activado y configurado) ---
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend_Up2Play/backend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Run Tests
        env:
          # Forzamos el perfil de test que usa H2
          SPRING_PROFILES_ACTIVE: test
          # Estas variables sobrescriben el yml si fuera necesario
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          # Al usar H2 en memoria, no necesitamos un servicio externo de base de datos
        run: mvn -B clean verify

      - name: Upload Test Reports
        if: always() # Se ejecuta aunque los tests fallen para que puedas ver qué pasó
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: Backend_Up2Play/backend/target/surefire-reports


